### ISSUE TITLE
Wasmer is not available on this system

### ISSUE THREAD

**Issue by merc1er** [sky-ring/rift#14]
I am unable to run `rift init` on both macOS (latest with Python 3.10.6) and Windows (Python 3.10+).

I am getting:

```
ImportError: Wasmer is not available on this system
```

After doing some research, it seems like the Wasmer package is not compatible with Python 3.10+ nor Windows ([source](https://github.com/wasmerio/wasmer-python/issues/126)).

**Comment by LaDoger** [comment]
Me too!

**Comment by AminRezaei0x443** [comment]
Thanks for reporting the bug! Could you kindly let us know if your macOS is an Apple M1 or M2? It would be great if you could also provide the specific architecture of your CPU and the version of your operating system so that we can try to reproduce the issue. I'll look into the possibility of adding a pure Python WASM interpreter as a fallback option as part of my investigation.

**Comment by AminRezaei0x443** [comment]
@merc1er Let's get back to this issue. Can you share specific details about CPU architecture of your macOS and Windows device? The issue about wasmer you mentioned is resolved and they're supporting windows completely. I think you're using an ARM device, Am I right?

**Comment by merc1er** [comment]
> @merc1er Let's get back to this issue. Can you share specific details about CPU architecture of your macOS and Windows device? The issue about wasmer you mentioned is resolved and they're supporting windows completely. I think you're using an ARM device, Am I right?

Sorry I missed the previous comment.

Yes I am using an M1 chip. Latest macOS version. I am not using windows.
